### ISSUE TITLE
Please provide an option for refresh interval

### ISSUE THREAD

**Issue by mishraspolaris** [ashish-r/cowin-vaccinator#1]
Now as the number of request per 15 min is restricted by govt, can you please provide a text box for it.

**Comment by ashish-r** [comment]
[Version 2.2](https://github.com/ashish-r/cowin-vaccinator/blob/build/bin/cowin-vaccinator.zip) now supports Rate Limit Pause. The bot automatically pauses after it reaches the 20 search rate limit in 15 mins and it automatically continues after the cool-down period.
